variable "region" {}
variable "vpcName" {}
variable "subnet_1" {}
variable "subnet_2" {}
variable "subnet_3" {}
variable "internet_gateway" {}
variable "route_table" {}
variable "availabilityZone1" {}
variable "availabilityZone2" {}
variable "availabilityZone3" {}
variable "vpcCIDRblock" {}
variable "subnet1CIDRblock" {}
variable "subnet2CIDRblock" {}
variable "subnet3CIDRblock" {}
variable "mapPublicIP" {}
variable "destinationCIDRblock" {}
variable "sshPort" {}
variable "httpsPort" {}
variable "httpPort" {}
variable "customTCPPort" {}
variable "egressPort" {}
variable "application_security" {}
variable "db_security" {}
variable "dbPort" {}
variable "connection" {}
variable "cidrBlocks" {}
variable "ssh_key_name" {}
variable "ami_build" {}
variable "storage" {}
variable "type" {}
variable "vol_size" {}
variable "engine" {}
variable "engine_version" {}
variable "db_identifier" {}
variable "db_instance_class" {}
variable "db_name" {}
variable "db_pswd" {}
variable "db_port" {}
variable "db_username" {}
variable "s3_bucketname" {}
variable "acltype" {}
variable "storage_class" {}
variable "tags_rule" {}
variable "transition_days" {}
variable "expiration_days" {}
variable "sse_algo" {}
variable "allocated_storage" {}
variable "backup_retention_period" {}
variable "user_account" {}
variable "user" {}
variable "S3bucketforCodeDeploy" {}
variable "deployment_app" {}
variable "deployment_app_group" {}
variable "aws_acm_arn" {}